config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'static_pages/about'

  resources :portfolios
  devise_for :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    mount_uploader :picture, PictureUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]

  # GET /portfolios
  # GET /portfolios.json
  def index
    @portfolios = Portfolio.all
  end

  # GET /portfolios/1
  # GET /portfolios/1.json
  def show
  end

  # GET /portfolios/new
  def new
    @portfolio = Portfolio.new
  end

  # GET /portfolios/1/edit
  def edit
  end

  # POST /portfolios
  # POST /portfolios.json
  def create
    @portfolio = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully created.' }
        format.json { render :show, status: :created, location: @portfolio }
      else
        format.html { render :new }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portfolios/1
  # PATCH/PUT /portfolios/1.json
  def update
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully updated.' }
        format.json { render :show, status: :ok, location: @portfolio }
      else
        format.html { render :edit }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolios/1
  # DELETE /portfolios/1.json
  def destroy
    @portfolio.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio
      @portfolio = Portfolio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portfolio_params
      params.require(:portfolio).permit(:name, :description, :picture)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home
    end

    def about
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Xablau2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="http://railsgirls.com/assets/bootstrap.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="/">Danno Aula</a>
          <ul class="nav">
            <a href="/portfolios">Portfolio</a>
            <a href="/static_pages/about">Sobre</a>
          </ul>
          <p class="navbar-text pull-right">
            <% if user_signed_in? %>
              Logged in as <strong><%= current_user.email %></strong>.
              <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
              <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
            <% else %>
              <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
              <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
            <% end %>
          </p>
        </div>
      </div>
    </div>

    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>

    <footer>
      <div class="container">
        IN Junior 2018
      </div>
    </footer>
  </body>
</html>

app/views/portfolios/_form.html.erb
<%= form_with(model: portfolio, local: true) do |form| %>
  <% if portfolio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(portfolio.errors.count, "error") %> prohibited this portfolio from being saved:</h2>

      <ul>
      <% portfolio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :portfolio_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :portfolio_description %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture, id: :portfolio_picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/edit.html.erb
<h1>Editing Portfolio</h1>

<%= render 'form', portfolio: @portfolio %>

<%= link_to 'Show', @portfolio %> |
<%= link_to 'Back', portfolios_path %>

app/views/portfolios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Portfolios</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @portfolios.each do |portfolio| %>
      <tr>
        <td><%= portfolio.name %></td>
        <td><%= portfolio.description %></td>
        <td><%= portfolio.picture %></td>
        <td><%= link_to 'Show', portfolio %></td>
        <% if current_user %>
          <td><%= link_to 'Edit', edit_portfolio_path(portfolio) %></td>
          <td><%= link_to 'Destroy', portfolio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user %>
  <%= link_to 'New Portfolio', new_portfolio_path %>
<% end %>

app/views/portfolios/new.html.erb
<h1>New Portfolio</h1>

<%= render 'form', portfolio: @portfolio %>

<%= link_to 'Back', portfolios_path %>

app/views/portfolios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @portfolio.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @portfolio.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@idea.picture_url, :width => 600) if @idea.picture.present? %>
</p>

<% if current_user %> <%= link_to 'Edit', edit_portfolio_path(@portfolio) %> <% end %> |
<%= link_to 'Back', portfolios_path %>

app/views/static_pages/about.html.erb
<h1>This is the about page</h1>

app/views/static_pages/home.html.erb
<h1>This is the home page</h1>